# Site settings
author: Cory Tveten
title: Programming Block
header-img: img/home-bg.png
email: corytveten@gmail.com
copyright_name: Cory Tveten
description: > # this means to ignore newlines until "baseurl:"
  Coding with Ruby 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  corytveten

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
